from hutil.Qt import QtCore, QtGui, QtWidgets
import os

scriptpath = os.path.dirname(os.path.realpath(__file__))


class Ui_Theme(object):
    def setupUi(self, Theme):
        Theme.setObjectName("Theme")
        Theme.setWindowModality(QtCore.Qt.NonModal)
        Theme.resize(450, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Theme.sizePolicy().hasHeightForWidth())
        Theme.setSizePolicy(sizePolicy)
        Theme.setMinimumSize(QtCore.QSize(100, 0))
        Theme.setBaseSize(QtCore.QSize(0, 0))
        Theme.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Theme)
        self.gridLayout.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.r1 = QtWidgets.QHBoxLayout()
        self.r1.setObjectName("r1")
        self.c1 = QtWidgets.QVBoxLayout()
        self.c1.setObjectName("c1")
        self.h3_c1 = QtWidgets.QHBoxLayout()
        self.h3_c1.setObjectName("h3_c1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h3_c1.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Theme)
        self.label.setObjectName("label")
        self.h3_c1.addWidget(self.label)
        self.text1btn = QtWidgets.QToolButton(Theme)
        self.text1btn.setObjectName("text1")
        self.h3_c1.addWidget(self.text1btn)
        self.text1 = QtWidgets.QLineEdit(Theme)
        self.text1.setObjectName("text1_txt")
        self.h3_c1.addWidget(self.text1)
        self.c1.addLayout(self.h3_c1)
        self.h4_c1 = QtWidgets.QHBoxLayout()
        self.h4_c1.setObjectName("h4_c1")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h4_c1.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(Theme)
        self.label_2.setObjectName("label_2")
        self.h4_c1.addWidget(self.label_2)
        self.text2btn = QtWidgets.QToolButton(Theme)
        self.text2btn.setObjectName("text2")
        self.h4_c1.addWidget(self.text2btn)
        self.text2 = QtWidgets.QLineEdit(Theme)
        self.text2.setObjectName("text2_txt")
        self.h4_c1.addWidget(self.text2)
        self.c1.addLayout(self.h4_c1)
        self.h2_c1 = QtWidgets.QHBoxLayout()
        self.h2_c1.setObjectName("h2_c1")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h2_c1.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(Theme)
        self.label_3.setObjectName("label_3")
        self.h2_c1.addWidget(self.label_3)
        self.stats1btn = QtWidgets.QToolButton(Theme)
        self.stats1btn.setObjectName("stats1")
        self.h2_c1.addWidget(self.stats1btn)
        self.stats1 = QtWidgets.QLineEdit(Theme)
        self.stats1.setObjectName("stats1_txt")
        self.h2_c1.addWidget(self.stats1)
        self.c1.addLayout(self.h2_c1)
        self.h1_c1 = QtWidgets.QHBoxLayout()
        self.h1_c1.setObjectName("h1_c1")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h1_c1.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(Theme)
        self.label_4.setObjectName("label_4")
        self.h1_c1.addWidget(self.label_4)
        self.stats2btn = QtWidgets.QToolButton(Theme)
        self.stats2btn.setObjectName("stats2")
        self.h1_c1.addWidget(self.stats2btn)
        self.stats2 = QtWidgets.QLineEdit(Theme)
        self.stats2.setObjectName("stats2_txt")
        self.h1_c1.addWidget(self.stats2)
        self.c1.addLayout(self.h1_c1)
        self.r1.addLayout(self.c1)
        self.c2 = QtWidgets.QVBoxLayout()
        self.c2.setObjectName("c2")
        self.h1_c2 = QtWidgets.QHBoxLayout()
        self.h1_c2.setObjectName("h1_c2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h1_c2.addItem(spacerItem4)
        self.label_8 = QtWidgets.QLabel(Theme)
        self.label_8.setObjectName("label_8")
        self.h1_c2.addWidget(self.label_8)
        self.toolButton_5 = QtWidgets.QToolButton(Theme)
        self.toolButton_5.setObjectName("toolButton_5")
        self.h1_c2.addWidget(self.toolButton_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(Theme)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.h1_c2.addWidget(self.lineEdit_2)
        self.c2.addLayout(self.h1_c2)
        self.h2_c2 = QtWidgets.QHBoxLayout()
        self.h2_c2.setObjectName("h2_c2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h2_c2.addItem(spacerItem5)
        self.label_7 = QtWidgets.QLabel(Theme)
        self.label_7.setObjectName("label_7")
        self.h2_c2.addWidget(self.label_7)
        self.toolButton_6 = QtWidgets.QToolButton(Theme)
        self.toolButton_6.setObjectName("toolButton_6")
        self.h2_c2.addWidget(self.toolButton_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(Theme)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.h2_c2.addWidget(self.lineEdit_3)
        self.c2.addLayout(self.h2_c2)
        self.h3_c2 = QtWidgets.QHBoxLayout()
        self.h3_c2.setObjectName("h3_c2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h3_c2.addItem(spacerItem6)
        self.label_6 = QtWidgets.QLabel(Theme)
        self.label_6.setObjectName("label_6")
        self.h3_c2.addWidget(self.label_6)
        self.toolButton_7 = QtWidgets.QToolButton(Theme)
        self.toolButton_7.setObjectName("toolButton_7")
        self.h3_c2.addWidget(self.toolButton_7)
        self.lineEdit_4 = QtWidgets.QLineEdit(Theme)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.h3_c2.addWidget(self.lineEdit_4)
        self.c2.addLayout(self.h3_c2)
        self.h4_c2 = QtWidgets.QHBoxLayout()
        self.h4_c2.setObjectName("h4_c2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h4_c2.addItem(spacerItem7)
        self.label_5 = QtWidgets.QLabel(Theme)
        self.label_5.setObjectName("label_5")
        self.h4_c2.addWidget(self.label_5)
        self.toolButton_8 = QtWidgets.QToolButton(Theme)
        self.toolButton_8.setObjectName("toolButton_8")
        self.h4_c2.addWidget(self.toolButton_8)
        self.lineEdit = QtWidgets.QLineEdit(Theme)
        self.lineEdit.setObjectName("lineEdit")
        self.h4_c2.addWidget(self.lineEdit)
        self.c2.addLayout(self.h4_c2)
        self.r1.addLayout(self.c2)
        self.gridLayout.addLayout(self.r1, 0, 0, 1, 1)
        self.r2 = QtWidgets.QVBoxLayout()
        self.r2.setObjectName("r2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.savetheme = QtWidgets.QPushButton(Theme)
        self.savetheme.setObjectName("savetheme")
        self.horizontalLayout_2.addWidget(self.savetheme)
        self.r2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.r2, 1, 0, 1, 1)

        self.retranslateUi(Theme)
        QtCore.QMetaObject.connectSlotsByName(Theme)

    def retranslateUi(self, Theme):
        _translate = QtCore.QCoreApplication.translate
        Theme.setWindowTitle(_translate("Theme", "Form"))
        self.label.setText(_translate("Theme", "Text1"))
        self.text1btn.setText(_translate("Theme", "..."))
        self.label_2.setText(_translate("Theme", "Text2"))
        self.text2btn.setText(_translate("Theme", "..."))
        self.label_3.setText(_translate("Theme", "Stats1"))
        self.stats1btn.setText(_translate("Theme", "..."))
        self.label_4.setText(_translate("Theme", "Stats2"))
        self.stats2btn.setText(_translate("Theme", "..."))
        self.label_8.setText(_translate("Theme", "TextLabel"))
        self.toolButton_5.setText(_translate("Theme", "..."))
        self.label_7.setText(_translate("Theme", "TextLabel"))
        self.toolButton_6.setText(_translate("Theme", "..."))
        self.label_6.setText(_translate("Theme", "TextLabel"))
        self.toolButton_7.setText(_translate("Theme", "..."))
        self.label_5.setText(_translate("Theme", "TextLabel"))
        self.toolButton_8.setText(_translate("Theme", "..."))
        self.savetheme.setText(_translate("Theme", "Save"))

class LinkLabel(QtWidgets.QLabel):
    def __init__(self, parent, text):
        super(LinkLabel, self).__init__(parent)

        self.setText(text)
        self.setTextFormat(QtCore.Qt.RichText)
        self.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.setOpenExternalLinks(True)