# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearcherSettings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearcherSettings(object):
    def setupUi(self, SearcherSettings):
        SearcherSettings.setObjectName("SearcherSettings")
        SearcherSettings.setWindowModality(QtCore.Qt.NonModal)
        SearcherSettings.resize(450, 211)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearcherSettings.sizePolicy().hasHeightForWidth())
        SearcherSettings.setSizePolicy(sizePolicy)
        SearcherSettings.setMinimumSize(QtCore.QSize(450, 0))
        SearcherSettings.setBaseSize(QtCore.QSize(0, 0))
        SearcherSettings.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(SearcherSettings)
        self.gridLayout.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerrow = QtWidgets.QHBoxLayout()
        self.headerrow.setObjectName("headerrow")
        self.projectTitle = QtWidgets.QLabel(SearcherSettings)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.projectTitle.setFont(font)
        self.projectTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.projectTitle.setObjectName("projectTitle")
        self.headerrow.addWidget(self.projectTitle)
        self.line_2 = QtWidgets.QFrame(SearcherSettings)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.headerrow.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.headerrow.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(SearcherSettings)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName("checkBox")
        self.headerrow.addWidget(self.checkBox)
        self.windowsize_chk = QtWidgets.QCheckBox(SearcherSettings)
        self.windowsize_chk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.windowsize_chk.setObjectName("windowsize_chk")
        self.headerrow.addWidget(self.windowsize_chk)
        self.verticalLayout_4.addLayout(self.headerrow)
        self.line = QtWidgets.QFrame(SearcherSettings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.secondrow = QtWidgets.QHBoxLayout()
        self.secondrow.setObjectName("secondrow")
        self.lang_cbox = QtWidgets.QComboBox(SearcherSettings)
        self.lang_cbox.setObjectName("lang_cbox")
        self.lang_cbox.addItem("")
        self.secondrow.addWidget(self.lang_cbox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.secondrow.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(SearcherSettings)
        self.label_3.setObjectName("label_3")
        self.secondrow.addWidget(self.label_3)
        self.maxresults_txt = QtWidgets.QSpinBox(SearcherSettings)
        self.maxresults_txt.setMinimum(1)
        self.maxresults_txt.setMaximum(9999)
        self.maxresults_txt.setObjectName("maxresults_txt")
        self.secondrow.addWidget(self.maxresults_txt)
        self.inmemory_chk = QtWidgets.QCheckBox(SearcherSettings)
        self.inmemory_chk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inmemory_chk.setTristate(False)
        self.inmemory_chk.setObjectName("inmemory_chk")
        self.secondrow.addWidget(self.inmemory_chk)
        self.verticalLayout_4.addLayout(self.secondrow)
        self.thirdrow = QtWidgets.QHBoxLayout()
        self.thirdrow.setObjectName("thirdrow")
        self.label_2 = QtWidgets.QLabel(SearcherSettings)
        self.label_2.setObjectName("label_2")
        self.thirdrow.addWidget(self.label_2)
        self.defaulthotkey_txt = QtWidgets.QLineEdit(SearcherSettings)
        self.defaulthotkey_txt.setToolTip("")
        self.defaulthotkey_txt.setReadOnly(True)
        self.defaulthotkey_txt.setObjectName("defaulthotkey_txt")
        self.thirdrow.addWidget(self.defaulthotkey_txt)
        self.hotkey_icon = QtWidgets.QToolButton(SearcherSettings)
        self.hotkey_icon.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.hotkey_icon.setObjectName("hotkey_icon")
        self.thirdrow.addWidget(self.hotkey_icon)
        self.verticalLayout_4.addLayout(self.thirdrow)
        self.fourthrow = QtWidgets.QHBoxLayout()
        self.fourthrow.setObjectName("fourthrow")
        self.label = QtWidgets.QLabel(SearcherSettings)
        self.label.setObjectName("label")
        self.fourthrow.addWidget(self.label)
        self.databasepath_txt = QtWidgets.QLineEdit(SearcherSettings)
        self.databasepath_txt.setObjectName("databasepath_txt")
        self.fourthrow.addWidget(self.databasepath_txt)
        self.dbpath_icon = QtWidgets.QToolButton(SearcherSettings)
        self.dbpath_icon.setObjectName("dbpath_icon")
        self.fourthrow.addWidget(self.dbpath_icon)
        self.verticalLayout_4.addLayout(self.fourthrow)
        self.fifthrow = QtWidgets.QHBoxLayout()
        self.fifthrow.setObjectName("fifthrow")
        self.label_4 = QtWidgets.QLabel(SearcherSettings)
        self.label_4.setObjectName("label_4")
        self.fifthrow.addWidget(self.label_4)
        self.test1_btn = QtWidgets.QPushButton(SearcherSettings)
        self.test1_btn.setObjectName("test1_btn")
        self.fifthrow.addWidget(self.test1_btn)
        self.cleardata_btn = QtWidgets.QPushButton(SearcherSettings)
        self.cleardata_btn.setObjectName("cleardata_btn")
        self.fifthrow.addWidget(self.cleardata_btn)
        self.verticalLayout_4.addLayout(self.fifthrow)
        self.line_3 = QtWidgets.QFrame(SearcherSettings)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.sixthrow = QtWidgets.QHBoxLayout()
        self.sixthrow.setObjectName("sixthrow")
        self.about_btn = QtWidgets.QToolButton(SearcherSettings)
        self.about_btn.setObjectName("about_btn")
        self.sixthrow.addWidget(self.about_btn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sixthrow.addItem(spacerItem2)
        self.debuglevel_cbx = QtWidgets.QComboBox(SearcherSettings)
        self.debuglevel_cbx.setObjectName("debuglevel_cbx")
        self.debuglevel_cbx.addItem("")
        self.debuglevel_cbx.addItem("")
        self.debuglevel_cbx.addItem("")
        self.sixthrow.addWidget(self.debuglevel_cbx)
        self.debugflag_chk = QtWidgets.QCheckBox(SearcherSettings)
        self.debugflag_chk.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.debugflag_chk.setObjectName("debugflag_chk")
        self.sixthrow.addWidget(self.debugflag_chk)
        self.discard_btn = QtWidgets.QPushButton(SearcherSettings)
        self.discard_btn.setObjectName("discard_btn")
        self.sixthrow.addWidget(self.discard_btn)
        self.save_btn = QtWidgets.QPushButton(SearcherSettings)
        self.save_btn.setObjectName("save_btn")
        self.sixthrow.addWidget(self.save_btn)
        self.verticalLayout_4.addLayout(self.sixthrow)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(SearcherSettings)
        QtCore.QMetaObject.connectSlotsByName(SearcherSettings)

    def retranslateUi(self, SearcherSettings):
        _translate = QtCore.QCoreApplication.translate
        SearcherSettings.setWindowTitle(_translate("SearcherSettings", "Form"))
        self.projectTitle.setText(_translate("SearcherSettings", "Settings"))
        self.checkBox.setText(_translate("SearcherSettings", "Use Animated Menus:"))
        self.windowsize_chk.setText(_translate("SearcherSettings", "Remember Search Window Size"))
        self.lang_cbox.setCurrentText(_translate("SearcherSettings", "English"))
        self.lang_cbox.setItemText(0, _translate("SearcherSettings", "English"))
        self.label_3.setText(_translate("SearcherSettings", "Maximum Search Results"))
        self.inmemory_chk.setText(_translate("SearcherSettings", "Use In-Memory Database"))
        self.label_2.setText(_translate("SearcherSettings", "Hotkey to use for opening unassigned items: "))
        self.defaulthotkey_txt.setPlaceholderText(_translate("SearcherSettings", "Double Click"))
        self.hotkey_icon.setText(_translate("SearcherSettings", "..."))
        self.label.setText(_translate("SearcherSettings", "Database location: "))
        self.dbpath_icon.setText(_translate("SearcherSettings", "..."))
        self.label_4.setText(_translate("SearcherSettings", "Maintenance utilities:"))
        self.test1_btn.setText(_translate("SearcherSettings", "Test Button 1"))
        self.cleardata_btn.setText(_translate("SearcherSettings", "Clear Data"))
        self.about_btn.setText(_translate("SearcherSettings", "..."))
        self.debuglevel_cbx.setItemText(0, _translate("SearcherSettings", "NONE"))
        self.debuglevel_cbx.setItemText(1, _translate("SearcherSettings", "TIMER"))
        self.debuglevel_cbx.setItemText(2, _translate("SearcherSettings", "ALL"))
        self.debugflag_chk.setText(_translate("SearcherSettings", "Debug Mode"))
        self.discard_btn.setText(_translate("SearcherSettings", "Discard"))
        self.save_btn.setText(_translate("SearcherSettings", "Save"))
