# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bugreport.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BugReport(object):
    def setupUi(self, BugReport):
        BugReport.setObjectName("BugReport")
        BugReport.setWindowModality(QtCore.Qt.NonModal)
        BugReport.resize(393, 172)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BugReport.sizePolicy().hasHeightForWidth())
        BugReport.setSizePolicy(sizePolicy)
        BugReport.setMinimumSize(QtCore.QSize(100, 0))
        BugReport.setBaseSize(QtCore.QSize(0, 0))
        BugReport.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(BugReport)
        self.gridLayout.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.secondrow = QtWidgets.QHBoxLayout()
        self.secondrow.setObjectName("secondrow")
        self.lineEdit = QtWidgets.QLineEdit(BugReport)
        self.lineEdit.setMinimumSize(QtCore.QSize(175, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.secondrow.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.secondrow)
        self.headerrow = QtWidgets.QHBoxLayout()
        self.headerrow.setObjectName("headerrow")
        self.lineEdit_2 = QtWidgets.QLineEdit(BugReport)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(175, 0))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.headerrow.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.headerrow)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(BugReport)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        spacerItem = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo = QtWidgets.QLabel(BugReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(120, 120))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:/Users/mosthated/Downloads/483688212.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(BugReport)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(BugReport)
        QtCore.QMetaObject.connectSlotsByName(BugReport)

    def retranslateUi(self, BugReport):
        _translate = QtCore.QCoreApplication.translate
        BugReport.setWindowTitle(_translate("BugReport", "Form"))
        self.lineEdit.setPlaceholderText(_translate("BugReport", "Name:"))
        self.lineEdit_2.setPlaceholderText(_translate("BugReport", "Contact:"))
        self.textEdit.setPlaceholderText(_translate("BugReport", "What was the issue?"))
        self.pushButton.setText(_translate("BugReport", "Submit Bug"))
