# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searcher_ui.ui'
#
# Created by: qtpy UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Searcher(object):
    def setupUi(self, Searcher):
        Searcher.setObjectName("Searcher")
        Searcher.setWindowModality(QtCore.Qt.WindowModal)
        Searcher.resize(1000, 329)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Searcher.sizePolicy().hasHeightForWidth())
        Searcher.setSizePolicy(sizePolicy)
        Searcher.setMinimumSize(QtCore.QSize(0, 0))
        Searcher.setBaseSize(QtCore.QSize(1000, 350))
        Searcher.setStyleSheet("QTreeWidget QHeaderView::section {\n"
"    font-size: 9pt;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Searcher)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(Searcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.searchfilter_btn = QtWidgets.QToolButton(self.frame)
        self.searchfilter_btn.setGeometry(QtCore.QRect(0, 0, 26, 20))
        self.searchfilter_btn.setBaseSize(QtCore.QSize(16, 16))
        self.searchfilter_btn.setStyleSheet("background-color: rgb(19, 19, 19);")
        self.searchfilter_btn.setArrowType(QtCore.Qt.NoArrow)
        self.searchfilter_btn.setObjectName("searchfilter_btn")
        self.horizontalLayout_3.addWidget(self.frame)
        self.searchbox_txt = QtWidgets.QLineEdit(Searcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(99)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbox_txt.sizePolicy().hasHeightForWidth())
        self.searchbox_txt.setSizePolicy(sizePolicy)
        self.searchbox_txt.setMinimumSize(QtCore.QSize(50, 0))
        self.searchbox_txt.setMouseTracking(False)
        self.searchbox_txt.setStyleSheet("background-color: rgb(19, 19, 19);")
        self.searchbox_txt.setFrame(False)
        self.searchbox_txt.setObjectName("searchbox_txt")
        self.horizontalLayout_3.addWidget(self.searchbox_txt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.searchresults_tree = QtWidgets.QTreeWidget(Searcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchresults_tree.sizePolicy().hasHeightForWidth())
        self.searchresults_tree.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.searchresults_tree.setFont(font)
        self.searchresults_tree.setMouseTracking(False)
        self.searchresults_tree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.searchresults_tree.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.searchresults_tree.setLineWidth(0)
        self.searchresults_tree.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.searchresults_tree.setAlternatingRowColors(True)
        self.searchresults_tree.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.searchresults_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.searchresults_tree.setObjectName("searchresults_tree")
        self.searchresults_tree.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.searchresults_tree)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.infobar = QtWidgets.QHBoxLayout()
        self.infobar.setObjectName("infobar")
        self.infobargrid = QtWidgets.QGridLayout()
        self.infobargrid.setObjectName("infobargrid")
        self.info_lbl = QtWidgets.QLabel(Searcher)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.info_lbl.setFont(font)
        self.info_lbl.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.info_lbl.setIndent(5)
        self.info_lbl.setObjectName("info_lbl")
        self.infobargrid.addWidget(self.info_lbl, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Searcher)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.infobargrid.addWidget(self.label, 1, 1, 1, 1)
        self.infobar.addLayout(self.infobargrid)
        self.gridLayout.addLayout(self.infobar, 3, 0, 1, 1)

        self.retranslateUi(Searcher)
        QtCore.QMetaObject.connectSlotsByName(Searcher)

    def retranslateUi(self, Searcher):
        _translate = QtCore.QCoreApplication.translate
        Searcher.setWindowTitle(_translate("Searcher", "Searcher"))
        self.searchfilter_btn.setText(_translate("Searcher", "..."))
        self.info_lbl.setText(_translate("Searcher", "Begin typing to search or click magnifying glass icon to display options"))
        self.label.setText(_translate("Searcher", "TextLabel"))
